#!/usr/bin/python -u
#
# autotest <control file> - run the autotest control file specified.
#
try:
    import autotest.common as common  # pylint: disable=W0611
except ImportError:
    import common  # pylint: disable=W0611

from autotest.client import autotest_local

if __name__ == '__main__':
    app = autotest_local.AutotestLocalApp()
    app.main()
