--- tiobench-0.3.3/Makefile.orig	2011-02-07 20:32:53.000000000 -0800
+++ tiobench-0.3.3/Makefile	2011-02-07 20:33:02.000000000 -0800
@@ -1,6 +1,6 @@
 # Makefile for tiotest
 
-CC=gcc
+CC?=gcc
 #CFLAGS=-O3 -fomit-frame-pointer -Wall
 CFLAGS=-O2 -Wall
 
@@ -14,7 +14,7 @@ CFLAGS=-O2 -Wall
 
 #DEFINES=
 
-LINK=gcc
+LINK=$(CC)
 EXE=tiotest
 PROJECT=tiobench
 # do it once instead of each time referenced
