diff -u -r blktrace_orig/Makefile blktrace/Makefile
--- blktrace_orig/Makefile	Mon Jul 28 15:10:40 2008
+++ blktrace/Makefile	Mon Jul 28 15:11:56 2008
@@ -1,8 +1,8 @@
 CC	= gcc
-CFLAGS	= -Wall -O2 -g -W
+CFLAGS	+= -Wall -O2 -g -W
 ALL_CFLAGS = $(CFLAGS) -D_GNU_SOURCE -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64
 PROGS	= blkparse blktrace verify_blkparse blkrawverify
-LIBS	= -lpthread
+LIBS	+= -lpthread
 SCRIPTS	= btrace
 
 ALL = $(PROGS) $(SCRIPTS) btt/btt btreplay/btrecord btreplay/btreplay \
@@ -34,7 +34,7 @@
 blkrawverify: blkrawverify.o
 	$(CC) $(ALL_CFLAGS) -o $@ $(filter %.o,$^)
 
-$(PROGS): | depend
+$(PROGS): depend
 
 docs:
 	$(MAKE) -C doc all
Only in blktrace: Makefile~
diff -u -r blktrace_orig/btreplay/Makefile blktrace/btreplay/Makefile
--- blktrace_orig/btreplay/Makefile	Mon Jul 28 15:10:40 2008
+++ blktrace/btreplay/Makefile	Mon Jul 28 15:12:36 2008
@@ -6,18 +6,18 @@
 #
 
 CC	= gcc
-CFLAGS	= -Wall -W -O2 -g
+CFLAGS	+= -Wall -W -O2 -g
 INCS	= -I. -I.. -I../btt
 OCFLAGS	= -UCOUNT_IOS -UDEBUG -DNDEBUG
 XCFLAGS	= -D_GNU_SOURCE -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64
 override CFLAGS += $(INCS) $(XCFLAGS) $(OCFLAGS)
 
 PROGS	= btrecord btreplay
-LIBS	= -laio -lrt
+LIBS	+= -laio -lrt
 
 all: depend $(PROGS)
 
-$(PROGS): | depend
+$(PROGS): depend
 
 docs:
 	$(MAKE) -C doc all
diff -u -r blktrace_orig/btt/Makefile blktrace/btt/Makefile
--- blktrace_orig/btt/Makefile	Mon Jul 28 15:10:40 2008
+++ blktrace/btt/Makefile	Mon Jul 28 15:12:54 2008
@@ -6,13 +6,13 @@
 #
 
 CC	= gcc
-CFLAGS	= -Wall -W -O2 -g
+CFLAGS	+= -Wall -W -O2 -g
 INCS	= -I. -I..
 XCFLAGS	= -D_GNU_SOURCE -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64
 override CFLAGS += $(INCS) $(XCFLAGS)
 
 PROGS	= btt
-LIBS	= $(PLIBS) $(ELIBS)
+LIBS	+= $(PLIBS) $(ELIBS)
 OBJS	= args.o bt_timeline.o devmap.o devs.o dip_rb.o iostat.o latency.o \
 	  misc.o output.o proc.o seek.o trace.o trace_complete.o trace_im.o \
 	  trace_issue.o trace_queue.o trace_remap.o trace_requeue.o \
