#!/bin/sh
APPDIR=`dirname $0`;
GWTDIR=`$APPDIR/gwt_dir`;
java  -cp "$APPDIR/src:$APPDIR/bin:$GWTDIR/gwt-user.jar:$GWTDIR/gwt-dev-linux.jar" com.google.gwt.dev.HostedMode -ea -startupUrl http://localhost:8000/afe/server/autotest.AfeClient/AfeClient.html "$@" autotest.AfeClient
