#!/bin/sh
APPDIR=`dirname $0`;
GWTDIR=`$APPDIR/gwt_dir`;
java  -cp "$APPDIR/src:$APPDIR/bin:$GWTDIR/gwt-user.jar:$GWTDIR/gwt-dev-linux.jar:$GWTDIR/gwt-incubator.jar" com.google.gwt.dev.HostedMode -ea -startupUrl http://localhost:8000/new_tko/server/autotest.EmbeddedTkoClient/EmbeddedTkoClientTest.html "$@" autotest.EmbeddedTkoClient
