#!/bin/sh
APPDIR=`dirname $0`;
GWTDIR=`$APPDIR/gwt_dir`;
java  \
  -cp "$APPDIR/src:$APPDIR/bin:$GWTDIR/gwt-user.jar:$GWTDIR/gwt-dev-linux.jar" \
  -Djava.awt.headless=true \
  com.google.gwt.dev.GWTCompiler -out "$APPDIR/www" "$@" autotest.TkoClient
