#!/bin/sh

# Work out which test this is.
test=`basename "$1"`

case "$test" in
???-barrier-unordered-*)
	# Any realistic testing of barriers will involve random ordering
	# of arrivals at the barrier, so we need to order the output
	# such that it is comparible.
	$0 XXX-barrier-ordered | sort
	;;
???-barrier-*)
	# Barriers are timeout based, so we need to drop all the noise.
	awk '
		/barrier: .* calling master/	{ next }
		/barrier: .* remaining: /	{ next }
						{ print }
	' | sed -e 's/start=[0-9][0-9]*/start=NNN/g' \
		-e 's/(127.0.0.1:[0-9][0-9]*)/(ADDR:PORT)/g'
	;;
*)
	cat -
	;;
esac
