#!/usr/bin/python -u

import sys
try:
    import autotest.common as common  # pylint: disable=W0611
except ImportError:
    import common  # pylint: disable=W0611
from autotest.cli import atest


sys.exit(atest.main())
