#!/usr/bin/python -u
"""
Autotest scheduler watcher.
"""
try:
    import autotest.common  # pylint: disable=W0611
except ImportError:
    import common  # pylint: disable=W0611

from autotest.scheduler import monitor_db_watcher

if __name__ == '__main__':
    monitor_db_watcher.main()
