#!/usr/bin/python -u
"""
Autotest scheduler watcher.
"""
try:
    import autotest.common
except ImportError:
    import common

from autotest_lib.scheduler import monitor_db_watcher

if __name__ == '__main__':
    monitor_db_watcher.main()
