#!/usr/bin/python -u
"""
Autotest scheduler.
"""
try:
    import autotest.common as common  # pylint: disable=W0611
except ImportError:
    import common  # pylint: disable=W0611

from autotest.scheduler import monitor_db

if __name__ == '__main__':
    monitor_db.main()
