*** unixbench-4.1.0/Makefile	Wed Jul 28 15:05:02 1999
--- unixbench-4.1.0.patch/Makefile	Fri Jan 21 10:56:32 2011
***************
*** 32,50 ****
  SHELL = /bin/sh
  #HZ = ????  	   #(read from environment)
  CFLAGS = -DTIME
! CC=gcc
  
  ## For Linux 486/Pentium, GCC 2.7.x and 2.8.x
! #OPTON = -O2 -fomit-frame-pointer -fforce-addr -fforce-mem -ffast-math \
  #	-m486 -malign-loops=2 -malign-jumps=2 -malign-functions=2
  ## For Linux, GCC previous to 2.7.0
! #OPTON = -O2 -fomit-frame-pointer -fforce-addr -fforce-mem -ffast-math -m486
  
! #OPTON = -O2 -fomit-frame-pointer -fforce-addr -fforce-mem -ffast-math \
  #	-m386 -malign-loops=1 -malign-jumps=1 -malign-functions=1
  
  ## For Solaris 2, or general-purpose GCC 2.7.x
! OPTON = -O2 -fomit-frame-pointer -fforce-addr -fforce-mem -ffast-math -Wall
  
  ## Very generic
  #OPTON = -O
--- 32,51 ----
  SHELL = /bin/sh
  #HZ = ????  	   #(read from environment)
  CFLAGS = -DTIME
! CC?=gcc
  
  ## For Linux 486/Pentium, GCC 2.7.x and 2.8.x
! # -O2 already turned -fforce-mem
! OPTON = -O2 -fomit-frame-pointer -fforce-addr -ffast-math \
  #	-m486 -malign-loops=2 -malign-jumps=2 -malign-functions=2
  ## For Linux, GCC previous to 2.7.0
! #OPTON = -O2 -fomit-frame-pointer -fforce-addr -ffast-math -m486
  
! #OPTON = -O2 -fomit-frame-pointer -fforce-addr -ffast-math \
  #	-m386 -malign-loops=1 -malign-jumps=1 -malign-functions=1
  
  ## For Solaris 2, or general-purpose GCC 2.7.x
! #OPTON = -O2 -fomit-frame-pointer -fforce-addr -fforce-mem -ffast-math -Wall
  
  ## Very generic
  #OPTON = -O
***************
*** 203,212 ****
  	$(CC) -o $(PROGDIR)/dhry2 ${CFLAGS} ${OPTON} $(SRCDIR)/dhry_1.o $(SRCDIR)/dhry_2.o 
  	cd $(SRCDIR); rm -f dhry_1.o dhry_2.o 
  $(PROGDIR)/dhry2reg: $(SRCDIR)/dhry_1.c $(SRCDIR)/dhry_2.c $(SRCDIR)/dhry.h 
! 	cd $(SRCDIR); $(CC) -c ${CFLAGS} -DREG=register -DHZ=${HZ} ${OPTON} dhry_1.c
! 	cd $(SRCDIR); $(CC) -c ${CFLAGS} -DREG=register -DHZ=${HZ} ${OPTON} dhry_2.c
! 	$(CC) -o $(PROGDIR)/dhry2reg ${CFLAGS} ${OPTON} $(SRCDIR)/dhry_1.o $(SRCDIR)/dhry_2.o
! 	cd $(SRCDIR); rm -f dhry_1.o dhry_2.o
  
  
  dhry2reg: $(SRCDIR)/dhry_1.c $(SRCDIR)/dhry_2.c $(SRCDIR)/dhry.h 
--- 204,213 ----
  	$(CC) -o $(PROGDIR)/dhry2 ${CFLAGS} ${OPTON} $(SRCDIR)/dhry_1.o $(SRCDIR)/dhry_2.o 
  	cd $(SRCDIR); rm -f dhry_1.o dhry_2.o 
  $(PROGDIR)/dhry2reg: $(SRCDIR)/dhry_1.c $(SRCDIR)/dhry_2.c $(SRCDIR)/dhry.h 
! 	cd $(SRCDIR); $(CC) -c ${CFLAGS} -DREG=register -DHZ=${HZ} ${OPTON} dhry_1.c -o dhry_1_reg.o
! 	cd $(SRCDIR); $(CC) -c ${CFLAGS} -DREG=register -DHZ=${HZ} ${OPTON} dhry_2.c -o dhry_2_reg.o
! 	$(CC) -o $(PROGDIR)/dhry2reg ${CFLAGS} ${OPTON} $(SRCDIR)/dhry_1_reg.o $(SRCDIR)/dhry_2_reg.o
! 	cd $(SRCDIR); rm -f dhry_1_reg.o dhry_2_reg.o
  
  
  dhry2reg: $(SRCDIR)/dhry_1.c $(SRCDIR)/dhry_2.c $(SRCDIR)/dhry.h 
