#!/usr/bin/env python


"""
This script attemps to make it trivial to create install the packages
needed for the operation of an Autotest server
"""


try:
    import autotest.common as common
except ImportError:
    import common


from autotest.client.shared import software_manager
from autotest.frontend.pkgdeps import PKG_DEPS


if __name__ == '__main__':
    software_manager.install_distro_packages(PKG_DEPS)
