#!/usr/bin/python -u
"""
Run an control file using the remote engine.

@copyright: 2007-2008 Martin J. Bligh <mbligh@google.com>, Google Inc.
@license: GPL v2
"""

try:
    import autotest.common as common  # pylint: disable=W0611
except ImportError:
    import common  # pylint: disable=W0611
from autotest.server import autoserv


if __name__ == '__main__':
    autoserv.main()
