#!/usr/bin/python -u

try:
    import autotest.common as common  # pylint: disable=W0611
except ImportError:
    import common  # pylint: disable=W0611
from autotest.database_legacy import migrate


if __name__ == '__main__':
    migrate.main()
