#!/usr/bin/python

import os, sys
import db
from frontend import *
from display import *

machine = sys.argv[1]
kernel_version = sys.argv[2]

print_kernel_machines_vs_test([machine], kernel_version)

