#!/usr/bin/python
import os, re, parse, db, sys

if len(sys.argv) < 2:
	raise "I need a path to the results directory"

topdir = sys.argv[1]
jobs_list = os.listdir(topdir)

jobs = {}
db = db.db(True)

for j in jobs_list:
	print 'looking for ' + j
	if db.find_job(j):              # Job has already been parsed
		continue
	job = parse.job(os.path.join(topdir, j), 'regression')
	if not job:
		continue
	print 'parsed ' + j
	if not job.kernel:
		continue
	print '%s %s' % (j, job.kernel.base)
	for test in job.tests:
		print "\t%s %s %s" % (test.dir, test.status, test.reason)
	db.insert_job(j, job)
