#!/usr/bin/python2.4
import os, re, parse

topdir = "/home/mirror/tko/abat"
index = "external.list"

jobs = {}

jobs_list = open(os.path.join(topdir, index), 'r').readlines()
jobs_list = [j.strip() for j in jobs_list]

for j in jobs_list:
	key = 'abat' + j
	job_dir = os.path.join(topdir, j)
	jobs[key] = job.job(job_dir)
	print key + ' ' + jobs[key].kernel
