; fio-mixed.job for autotest

[global]
name=fio-sync
;directory=tmpfiles
rw=randrw
rwmixread=67
rwmixwrite=33
bsrange=16K-256K
direct=0
end_fsync=1
verify=crc32
;ioscheduler=x
numjobs=4

[file1]
size=100M
ioengine=sync
mem=malloc

[file2]
stonewall
size=100M
ioengine=aio
mem=shm
iodepth=4

[file3]
stonewall
size=100M
ioengine=mmap
mem=mmap
direct=1

[file4]
stonewall
size=100M
ioengine=splice
mem=malloc
direct=1
